brew "fish"
brew "shellcheck"
brew "the_silver_searcher"
brew "gpg"
brew "jj"

cask "1password-cli"
cask "alfred"
cask "firefox"
cask "font-fira-code"
cask "hammerspoon"
cask "macvim-app"
cask "tresorit"
cask "wezterm"
cask "zoom"
