brew("fish")
brew("gpg")
brew("herdr")
brew("jj")
brew("shellcheck")
brew("the_silver_searcher")

cask("1password-cli")
cask("alfred")
cask("firefox")
cask("font-fira-code")
cask("hammerspoon")
cask("macvim-app")
cask("muteme")
cask("tresorit")
cask("wezterm")
cask("zoom")
